version: "3.8"
services:
  mysqldb:
    container_name: mysql-container
    image: mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    networks:
      - apinetwork

  achatapplication:
    container_name: achatapplication-container
    image: z4rga/achat-app:1.0.0
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - apinetwork

  angularfrontend:
    container_name: angularfrontend-container
    image: z4rga/achat-front:1.0
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - apinetwork

volumes:
  db_data: {}
networks:
  apinetwork:
    driver: bridge
